name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Definir TAG/SERVICE/ENV por branch
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "TAG=prod" >> $GITHUB_ENV
            echo "SERVICE=prova-zambom-image" >> $GITHUB_ENV
            echo "NODE_ENV=production" >> $GITHUB_ENV
            echo "DB_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          fi

      - name: Build with Cloud Build (tag do ambiente)
        run: |
          IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/prova-zambom/prova-zambom-image:${TAG}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          gcloud builds submit --tag "$IMAGE" .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE" \
            --image "$IMAGE" \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars "NODE_ENV=$NODE_ENV,DATABASE_URL=$DB_URL"
